fix Primitives (Estimator) documentation typo
Qiskit/qiskit pull request #10301
Opened 2023-06-16 17:12 UTC by tommasofioravanti

### Summary
I was reading the overview of Estimator class and I found a typo in the documentation " ... yields **the a** list of expectation values plus optional..." (the two articles before "list" word).

### Details and comments
I fixed the bug to make reading the textbook as clear and smooth as possible for readers.

2023-06-16 17:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=10301) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=10301) before we can accept your contribution.<br/><hr/>**Tommaso Fioravanti** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=10301) it.</sub>

2023-06-16 17:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=10301) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=10301) before we can accept your contribution.<br/><hr/>**Tommaso Fioravanti** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=10301) it.</sub>

2023-06-19 01:23 UTC, ikkoham requested changes
Nice catch! LGTM if the linter is passed.

2023-07-07 00:14 UTC, 1ucian0 commented
Thanks @tommasofioravanti for the fix! Dont forget to sign the CLA and take a look to linting issue.

2024-07-05 10:34 UTC, 1ucian0 commented
@tommasofioravanti  without CLA, we cannot merge. Closing this as stalling.

2024-07-05 10:34 UTC, closed without merging