Removed code and tests depreciated in 0.21
Qiskit/qiskit pull request #10754
Opened 2023-09-01 06:45 UTC by Raghav-Bell

It fixes #10748 

### Summary

### Details and comments

2023-09-01 06:49 UTC, Raghav-Bell commented
`tox` test fails on `test\benchmarks\scheduling_passes.py` as it  only contains check for `TimeUnitConversion` . Should we keep `test\benchmarks\scheduling_passes.py` or not ? also i have removed most of the  tests for depreciated or removed `classes`. Please let me know if i am missing something.

2023-09-01 12:54 UTC, woodsp-ibm commented
I am unsure about `optimizers/spsa` - mainly in regards of whatever upgrade note you do for the release note (which has yet to be included here). The optimizers are part of algorithms - I did have a prior issue #9866 that included addressing spsa but when the whole of algorithms was deprecated in the last release I simply closed it. I know in other similar issues that @1ucian0 created any deprecation removal for algorithms was dropped - maybe that's the simplest course here @1ucian0? - not to change spsa here given the whole module its part of is already deprecated - that will avoid any issues around including it or not in the release note

2023-09-01 14:05 UTC, ElePT commented
I'm with @woodsp-ibm, I think it's best to leave algorithms-related code untouched until its removal.

2023-09-01 14:54 UTC, 1ucian0 commented
I agree that leaving out `qiskit.algorithms` from this removal is probably the best option (the list was created by a program, my apologies for including it originally.

2023-09-02 21:07 UTC, 1ucian0 commented on qiskit/algorithms/optimizers/spsa.py
>          Args:
```suggestion

        Args:
```

2023-09-02 21:07 UTC, 1ucian0 commented on qiskit/algorithms/optimizers/spsa.py
>          Returns:
```suggestion

        Returns:
```

2023-09-04 08:51 UTC, 1ucian0 requested changes
I moving this PR as draft, as it seems to need some extra work before reviewing. Don't forget to add a release note:
> create a release note in the category upgrade:. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

2023-09-14 10:44 UTC, 1ucian0 commented
Take a look to the conflicts! When ready for review, hit `Ready for review`.

2023-09-14 16:42 UTC, Raghav-Bell commented
@1ucian0 These conflicts are due to  recent merge of PR #10753  as in the PR #10753  `classes ALAPSchedule, AlignMeasures, DynamicalDecoupling` are changed which are deprecated in `0.21` (removed with merge of this PR).  I think we can merge this PR. Please let me know what do you think on this ?

2023-09-16 20:31 UTC, 1ucian0 commented
> These conflicts are due to recent merge of PR #10753 as in the [...] Please let me know what do you think on this ?

I mean, by "take a look" I wanted to say "resolve the conflicts". Sometimes my word choice is not the best. My bad.

2023-09-17 04:56 UTC, Raghav-Bell commented
@1ucian0 It seems these conflicts can not be resolved by me (refer: [How do I fix a merge conflict due to removal of a file in a branch?](https://stackoverflow.com/questions/1380670/how-do-i-fix-a-merge-conflict-due-to-removal-of-a-file-in-a-branch)) Maintainers should remove `qiskit/transpiler/passes/scheduling/alap.py`, `qiskit/transpiler/passes/scheduling/alignments/align_measures.py` and `qiskit/transpiler/passes/scheduling/dynamical_decoupling.py` while merging .  If that is not the case please help me to resolve the conflicts .

2023-09-20 04:58 UTC, Raghav-Bell commented
Following test is failing on windows , let me check the fix and resolve the conflict:
https://github.com/Qiskit/qiskit/blob/e62c86bbc2720883270641f1c154743a657cfca8/test/python/algorithms/test_measure_error_mitigation.py#L56

2023-09-22 14:13 UTC, 1ucian0 requested changes
Thanks for taking care of this! It is a complicated one. I think some of the tests should be migrated instead of removed. Would you like to have a shoot at that?

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +    use generic :class:`.transpiler.passes.GateDirection`.
```suggestion
    The transpilation pass ``qiskit.transpiler.passes.CXDirection`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use the more generic :class:`~.GateDirection` pass.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The function :func:`~qiskit.execute_function.execute`
    does not accept the arguments `qobj_id` and  `qobj_header` any more.
    Their use was deprecated in Qiskit 0.37 (with Terra 0.21), released on June 2022.    
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The transpilation pass ``qiskit.transpiler.passes.ALAPSchedule`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022 and replaced by 
    :class:`~.transpiler.passes.ALAPScheduleAnalysis`, which is an
    analysis pass that require
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
  - |
    The transpilation pass ``qiskit.transpiler.passes.ASAPSchedule`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022. It has been superseded by
    :class:`~.ASAPScheduleAnalysis` and the new scheduling workflow.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The transpilation pass ``qiskit.transpiler.passes.DynamicalDecoupling`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use :class:`~.transpiler.passes.PadDynamicalDecoupling`, which performs the same
    function but requires scheduling and alignment analysis passes to run prior to it.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The transpilation pass ``qiskit.transpiler.passes.AlignMeasures`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use :class:`~.ConstrainedReschedule`, which performs the same function 
    and also supports aligning to additional timing constraints.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The transpilation pass ``qiskit.transpiler.passes.CXDirection`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use the more generic :class:`~.GateDirection` pass.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The transpilation pass ``qiskit.transpiler.passes.CheckCXDirection`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use the more generic :class:`~.CheckGateDirection` pass.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
    The methods ``to_dict`` in the classes :class:`.pulse.transforms.AlignmentKind`,
    `.pulse.transforms.AlignEquispaced`, and :class:`.pulse.transforms.AlignFunc` are removed.
    They were deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
```

2023-09-22 14:13 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
- |
   The argument ``circuits`` in the method :meth:`qiskit.qpy.interface.dump`
   is removed as its usage was deprecated 
   in Qiskit 0.37 (with Terra 0.21), released on June 2022.
   Instead, use the argument ``programs``, which behaves identically.
```

2023-09-22 14:13 UTC, 1ucian0 commented on test/benchmarks/scheduling_passes.py
I'm not fully sure, but I think these tests should be migrated, as they are `test/benchmarks`

2023-09-22 14:13 UTC, 1ucian0 commented on test/python/transpiler/test_instruction_alignments.py
Similarly, these tests should be migrated to the new workflow, I think.

2023-09-23 07:22 UTC, Raghav-Bell commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
From next PR onwards, I will try to make release notes more user oriented. 😅

2023-09-23 07:24 UTC, Raghav-Bell commented on test/benchmarks/scheduling_passes.py
I think they are already migrated here in [benchmarks/scheduling_passes.py](https://github.com/Qiskit/qiskit/blob/main/test/benchmarks/scheduling_passes.py).

2023-09-23 07:26 UTC, Raghav-Bell commented on test/python/transpiler/test_instruction_alignments.py
I have checked similiar test. in [benchmarks/transpiler_levels.py](https://github.com/Qiskit/qiskit/blob/main/test/benchmarks/transpiler_levels.py). Can you please elaborate about this? Should we add a github workflow for them ?

2023-10-18 10:40 UTC, 1ucian0 commented on qiskit/transpiler/passes/__init__.py
> +
```suggestion
```

2023-10-18 10:41 UTC, 1ucian0 commented on qiskit/execute_function.py
> +
```suggestion
```

2023-10-18 10:41 UTC, 1ucian0 commented on qiskit/transpiler/passes/scheduling/__init__.py
> +
```suggestion
```

2023-10-18 10:43 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
```

2023-10-18 10:44 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
```

2023-10-18 10:46 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +
```suggestion
```

2023-10-18 10:47 UTC, 1ucian0 commented on releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
> +    Instead, use the argument ``programs``, which behaves identically.
```suggestion
  - |
    The transpilation pass ``qiskit.transpiler.passes.AlignMeasures`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use :class:`~.ConstrainedReschedule`, which performs the same function 
    and also supports aligning to additional timing constraints.
  - |
    The transpilation pass ``qiskit.transpiler.passes.CXDirection`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use the more generic :class:`~.GateDirection` pass.
  - |
    The transpilation pass ``qiskit.transpiler.passes.CheckCXDirection`` is removed. It use was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use the more generic :class:`~.CheckGateDirection` pass.
  - |
    The methods ``to_dict`` in the classes :class:`.pulse.transforms.AlignmentKind`,
    `.pulse.transforms.AlignEquispaced`, and :class:`.pulse.transforms.AlignFunc` are removed.
    They were deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
  - |
    The argument ``circuits`` in the method :meth:`qiskit.qpy.interface.dump`
    is removed as its usage was deprecated 
    in Qiskit 0.37 (with Terra 0.21), released on June 2022.
    Instead, use the argument ``programs``, which behaves identically.
```

2023-10-18 10:48 UTC, 1ucian0 commented on qiskit/execute_function.py
> +
```suggestion
```

2023-10-18 11:14 UTC, 1ucian0 approved these changes
I migrated the benchmark tests to the new style. The rest, let's merge. Thanks!

2023-10-18 14:09 UTC, merged