Deprecate dense Operator Estimator observables
Qiskit/qiskit pull request #11056
Opened 2023-10-19 19:16 UTC by chriseclectic

### Summary

This deprecates passing Operator and other dense `BaseOperator` subclasses as observables in `Estimator.run`. These were implicitly converted to SparsePauliOps by the Estimator, so now should be explicitly converted to `SparsePauliOps` by the user instead.

### Details and comments

2023-10-23 06:40 UTC, t-imamichi submitted a review, later dismissed
LGTM

2023-10-23 07:47 UTC, t-imamichi commented
I made a PR to fix unit test errors. A unit test of gradient uses `Operator` as input.
https://github.com/chriseclectic/qiskit-terra/pull/58

2024-01-09 19:58 UTC, ihincks approved these changes, later dismissed

2024-01-09 20:14 UTC, jakelishman commented
New-deprecation PRs intended for 0.46 want to be targetted directly at `stable/0.46`, not `main`.  I briefly changed the base branch, but it's from too new a commit for me to do without a force-push.  The head commit should be rebased onto `stable/0.46`.

2024-01-09 21:29 UTC, chriseclectic commented
@jakelishman It looks like there are other primitives deprecation's from previously merged PRs not included in 0.46, such as conversion #11052 #11055. Do we need to merge into main, and then open a separate PR to backport these to stable/0.46 ?

2024-01-09 21:46 UTC, jakelishman commented
Luciano noticed #11055 and took / is taking care of it with #11520, but we didn't know about #11052.  That needs applying to 0.46 too.  We can leave the commits on main for now, provided another PR before 1.0 tidies them up.  I can get the bot to prepare a port of #11052 to stable/0.46.

The difference to normal here is that the current backport branch is `stable/0.45`, and the development branch `main` is for 1.0.  New deprecations for 0.46 aren't eligible to be made in the 0.45.x series, and they shouldn't be on `main` (the feature should be removed), which is why the PRs need making against the unreleased `stable/0.46` directly; we're treating that as the development branch of 0.46.

2024-01-10 08:59 UTC, 1ucian0 commented on qiskit/primitives/utils.py
> +        warnings.warn(
Considere adding a docstring note (similar to https://github.com/Qiskit/qiskit/pull/11520/files#diff-0094a250bbe85d99bff3279e6eaea98adaffcdb59e89773c76cb60be18a19675R157-R161).

2024-01-10 09:01 UTC, 1ucian0 commented on qiskit/primitives/utils.py
> +            " in Qiskit 1.0. You should explicitly convert to a SparsePauli op using"
```suggestion
            " observable arguments is deprecated as of Qiskit 0.46 and will be removed"
            " in Qiskit 1.0. You should explicitly convert to a SparsePauli op using"
```

2024-01-10 09:01 UTC, 1ucian0 requested changes
Thanks!

Just checking the style, consider adding a docstring note and a release note.

2024-01-10 15:11 UTC, chriseclectic commented
@jakelishman @1ucian0 since it would involve a full rebase to change the target branch I'll open a second PR for adding this to 0.46

2024-01-10 15:12 UTC, jakelishman commented
@Mergifyio backport stable/0.46

2024-01-10 15:12 UTC, jakelishman commented
ok, now the bot will just do it for you when this merges

2024-01-10 15:17 UTC, chriseclectic commented
Replaced by #11535

2024-01-10 15:17 UTC, closed without merging