Fix typo in README.md
Qiskit/qiskit pull request #11078
Opened 2023-10-22 00:34 UTC by Chandanmali

### Summary
change wrong words
change grammer

2023-10-22 00:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=11078) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=11078) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=11078) it.</sub>

2023-10-27 21:24 UTC, mtreinish requested changes
Thanks for taking the time to draft a pull request and submit it and your first contribution to Qiskit! I left some comments inline, but I think most of the typos you're correcting aren't actually typos or issues in the README text. There was the one change to capitalization on L74 that I think was fine though. So if you reduce the changes in your PR so it's just that single line this will be ok to merge.

2023-10-27 21:24 UTC, mtreinish commented on README.md
> +Qiskit also provides a lower-level abstract interface for describing quantum backends. This interface, is located in
This is actually correct usage with the commas surrounding it.

2023-10-27 21:24 UTC, mtreinish commented on README.md
> +To install from the source, follow the instructions in the [documentation](https://qiskit.org/documentation/contributing_to_qiskit.html#install-install-from-source-label).
"install from source" is a pretty common phrasing to describe installing a program from its source code.

2023-10-27 21:24 UTC, mtreinish commented on README.md
> +## Acknowledgments
Both of these are valid spellings of the word, I'm not sure we need to change it.

2023-10-27 21:24 UTC, mtreinish commented on README.md
> +on how to get access to use these systems.
I feel like the previous wording is more descriptive as it's distinguishing that getting access and using the systems are different tasks.

2023-10-27 21:24 UTC, mtreinish commented on README.md
> +documentation on potential breaking changes on upgrades and new features.
The singular is correct here, because "upgrade" is the action being taken.

2024-04-03 09:39 UTC, 1ucian0 approved these changes
I left the L74 change only.

2024-04-12 21:05 UTC, mtreinish approved these changes

2024-04-12 21:48 UTC, merged