Raise error eagerly on bad unitary synthesis method
Qiskit/qiskit pull request #11367
Opened 2023-12-04 09:59 UTC by rupeshknn

### Summary
`generate_preset_pass_manager` now raises an error the pass manager is created, not when it is run.

Fixes #11355

2023-12-04 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=11367) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=11367) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=11367) it.</sub>

2023-12-04 13:43 UTC, kevinsung requested changes
Thanks! Please add a test.

2023-12-04 14:27 UTC, rupeshknn commented
Do you have a recommendation for where the test should be located? I couldn't find test files (within synthesis) that check whether a particular error was raised.

 Or I could add one where the pass manager is tested. https://github.com/Qiskit/qiskit/blob/main/test/python/transpiler/test_preset_passmanagers.py

2023-12-04 20:58 UTC, rupeshknn commented
I've added the test to `test/python/transpiler/test_stage_plugin.py:`

2023-12-04 23:35 UTC, kevinsung approved these changes, later dismissed
Thank you!

2023-12-04 23:44 UTC, kevinsung commented on releasenotes/notes/move-synthesis-plugin-error-61e3683bf5a0c225.yaml
> +    the pass manager is created, not when it is run.
```suggestion
    when the pass manager is created, not when it is run.
```

2023-12-04 23:44 UTC, kevinsung submitted a review, later dismissed

2023-12-05 02:54 UTC, jakelishman approved these changes
Thank you!

2023-12-05 05:46 UTC, merged