`SequenceIR` - convert `.flatten` into a pass
Qiskit/qiskit pull request #12038
Opened 2024-03-18 21:28 UTC by TsafrirA

### Summary
#11951 introduced `SequenceIR` with a built it `.flatten()` method. It was later decided that all operations altering the IR should be performed as part of compiler passes. To this end, this PR converts the flatten method into a dedicated pass.

It should be noted that with `.flatten()` removed, `.draw()` can no longer draw the flattened version of the IR, as it could before (cyclic imports).

2024-03-19 09:40 UTC, nkanazawa1989 requested changes
Very quick review. I'll review this again after this passes test.

2024-03-19 09:40 UTC, nkanazawa1989 commented on qiskit/pulse/compiler/passes/flatten.py
> +                sub_block.flatten(inplace=True)
Does this exist?

2024-03-19 09:40 UTC, nkanazawa1989 commented on qiskit/pulse/compiler/passes/flatten.py
> +                if initial_time is not None:
Do you need this check?

2024-03-19 11:41 UTC, TsafrirA commented on qiskit/pulse/compiler/passes/flatten.py
> +                sub_block.flatten(inplace=True)
-facepalm-

2024-03-19 11:42 UTC, TsafrirA commented on qiskit/pulse/compiler/passes/flatten.py
> +                if initial_time is not None:
Good catch. Thanks!

2024-03-21 13:09 UTC, nkanazawa1989 reviewed
Minor comments. This looks good to go.

2024-03-21 13:09 UTC, nkanazawa1989 commented on qiskit/pulse/compiler/passes/flatten.py
> +        # TODO : Verify that the block\sub blocks are sequenced correctly?
Is this addressed by the sequence check in the _flatten function?

2024-03-21 13:09 UTC, nkanazawa1989 commented on qiskit/pulse/compiler/passes/flatten.py
> +    def _flatten(self, prog: SequenceIR) -> SequenceIR:
```suggestion
    def _flatten_recursion(self, prog: SequenceIR) -> SequenceIR:
```
To align with your convention.

2024-03-21 20:48 UTC, TsafrirA commented on qiskit/pulse/compiler/passes/flatten.py
> +        # TODO : Verify that the block\sub blocks are sequenced correctly?
I wasn't sure if we should verify the validity of the sequences. Now that I think of it, we verify that everything is scheduled, and that should be enough.

2024-03-22 02:04 UTC, nkanazawa1989 approved these changes
LGTM

2024-03-22 02:04 UTC, merged