Added the ctrl_state parameter to mcx() function
Qiskit/qiskit pull request #12050
Opened 2024-03-20 13:03 UTC by elucidator8918

### Description:

This PR addresses a feature request (#12044) to enhance the functionality of the mcx function in the quantum circuit library. Currently, the mcx function lacks a ctrl_state parameter, limiting its flexibility in certain quantum operations. 

The proposed change modifies the mcx function to include a ctrl_state parameter, allowing users to specify the control state of the multi-controlled X gate. This parameter can accept either a decimal value or a bitstring and defaults to controlling the '1' state if not provided.

### Expected Behavior:
Upon calling the mcx function, users can now pass the ctrl_state parameter to specify the control state for the multi-controlled X gate. This enhancement significantly enhances the functionality and flexibility of the function, enabling users to perform more complex quantum operations efficiently.

### Implementation Details:
- Modified the mcx function to accept the ctrl_state parameter.

@ShellyGarion: Please review the changes and provide feedback. Thank you :D

2024-03-20 13:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=12050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=12050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=12050) it.</sub>

2024-03-20 13:34 UTC, ShellyGarion commented
@elucidator8918 - Thanks for your contribution to Qiskit. 
It seems that you have some lint (black) errors.
Could you add some tests [here](https://github.com/Qiskit/qiskit/blob/main/test/python/circuit/test_controlled_gate.py) ?

2024-03-20 13:45 UTC, elucidator8918 commented
@ShellyGarion I think I know the linting mistake I made. Can I create another PR and resolve this?

2024-03-20 13:53 UTC, ShellyGarion commented
> @ShellyGarion I think I know the linting mistake I made. Can I create another PR and resolve this?

You can add commits to this PR

2024-03-20 14:32 UTC, elucidator8918 commented
@ShellyGarion The checks got passed :) only review is required

2024-03-20 14:59 UTC, ShellyGarion commented on qiskit/circuit/quantumcircuit.py
> +            "noancilla": MCXGrayCode(num_ctrl_qubits,ctrl_state=ctrl_state),
I think there should be a space after the comma (CI checks seem to be stuck now).

2024-03-20 15:01 UTC, ShellyGarion requested changes
Could you add some tests [here](https://github.com/Qiskit/qiskit/blob/main/test/python/circuit/test_controlled_gate.py) ?

2024-03-20 19:55 UTC, elucidator8918 commented
@ShellyGarion added some unit tests 

waiting for review :)

2024-03-21 06:52 UTC, ShellyGarion requested changes
Please also add release notes for the new feature.

2024-03-26 08:03 UTC, ShellyGarion requested changes
LGTM, I only have a few minor comments.

2024-03-26 08:03 UTC, ShellyGarion commented on test/python/circuit/test_controlled_gate.py
> +        See issue: https://github.com/Qiskit/qiskit-terra/issues/12050
Note that it's a PR and not an issue. We usually don't add the links.

2024-03-26 08:03 UTC, ShellyGarion commented on test/python/circuit/test_controlled_gate.py
> +    @data((4, [0, 1, 2], 3, "010"), (4, [2, 1, 3], 0, "010"))
perhaps one of the "010" could be an int and not a string?

2024-03-26 08:03 UTC, ShellyGarion commented on releasenotes/notes/added-parameter-ctrl_state-mcx-816dcd80e459a5ed.yaml
> +    Added ctrl_state parameter to mcx() function.
mcx() should be written as :func:`.QuantumCircuit.mcx()` 
also ctrl_state should be emphasized accordingly
(also in the other places in the release notes)

2024-03-27 07:18 UTC, ShellyGarion approved these changes
LGTM! thanks @elucidator8918

2024-03-27 18:03 UTC, alexanderivrii approved these changes
Thank you for the contribution! Given Shelly's approval, this can be merged,

2024-03-27 18:37 UTC, merged