add a new parameter num_qubits_distribution to random_circuit
Qiskit/qiskit pull request #12475
Opened 2024-05-29 03:28 UTC by KoheiSuda

### Summary
fixes #12059 
This PR extends the random_circuit function in Qiskit to allow users to specify a distribution num_operand_distribution that defines the ratio of 1-qubit, 2-qubit, ..., n-qubit gates in the generated random circuit. For example, calling random_circuit with num_operand_distribution={1: 0.5, 2: 0.5} will produce random circuits with approximately 50% single-qubit gates and 50% two-qubit gates, while disallowing gates with more than 2 qubits.

Additionally, the following points have been addressed:
> The parameter max_operands should take precedence, i.e. if max_operands is set, draw a random distribution num_operand_distribution. Raise an error if sum(num_operand_distribution.values()) != 1.0 or if max_operands is set at the same time as num_operand_distribution or if any key in num_operand_distribution is larger than the largest available n-qubit gate (see get_standard_gate_name_mapping).

### Details and comments
I worked on this issue as part of [unitaryHACK](https://unitaryhack.dev/), so please assign this issue to me if this PR is accepted.

2024-05-29 03:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=12475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=12475) before we can accept your contribution.<br/><hr/>**KoheiSuda** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=12475) it.</sub>

2024-05-29 03:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=12475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=12475) before we can accept your contribution.<br/><hr/>**KoheiSuda** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=12475) it.</sub>

2024-05-29 13:10 UTC, sbrandhsn commented
Dear Kohei-san, thanks for showing interest in this issue. I will be on vacation and look into this PR next week! In the meantime make yourself familiar with https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md and the unitaryhack rules (if you have not already). :-)

2024-06-04 15:24 UTC, sbrandhsn requested changes
Thanks for this contribution @KoheiSuda! :-) This looks like an elegant solution that needs a couple of modifications before it can be accepted.
- There are formatting issues which causes our CI to fail. Please run `tox -eblack` and `tox -elint-incr` locally to figure out what needs to be changed.
- I think I made a mistake when specifying the precedence of `max_operands`, sorry! Having both set, `max_operands` and `num_operand_distribution` set is fine, please revert the initial default value of `max_operands`. If `num_operand_distribution` is not set but `max_operands` is set, draw a random `num_operand_distribution` and continue with your code or use the initial code.
- Please add a test case with a distribution that disallows single-qubit gates, i.e. with {1:0, …}. I think some logic around how single-qubit gates are used to fill the non-used qubits in layer would fail such a test case with the current code.  
- Please add a test case with some distribution and specify a particularly long `depth` as a parameter. This should make your `num_operand_distribution` match closely what is contained in the returned random circuit.

2024-06-06 08:22 UTC, KoheiSuda commented
@sbrandhsn 
Thank you for your thoughtful advice!

> Please add a test case with a distribution that disallows single-qubit gates, i.e. with {1:0, …}. I think some logic around how single-qubit gates are used to fill the non-used qubits in layer would fail such a test case with the current code.

I have a question. If a distribution disallows single-qubit gates, how should I fill the non-used qubits in layer?

2024-06-07 09:58 UTC, sbrandhsn commented
Dear @KoheiSuda, I'm sorry but a PR was submitted by a different user that addresses https://github.com/Qiskit/qiskit/issues/12059 completely. Unfortunately, unitaryHACK explicitly allows multiple developers to work on the same issue at once ( https://unitaryhack.dev/rules/ ) and essentially requires us to select the first valid PR for the bounty. Qiskit still has open unitaryHACK issues available at https://github.com/Qiskit/qiskit/issues?q=is%3Aopen+label%3Aunitaryhack-bounty+is%3Aissue that (partially) attracted interest by other developers. 

Apart from this, I was very happy about your elegant contribution so far and can only encourage you to continue your good work on open source projects that you find interesting! :-)

2024-06-08 12:01 UTC, KoheiSuda commented
@sbrandhsn 
OK, Thank you for your reviewing!

2026-01-15 01:45 UTC, jakelishman commented
I'll close this as I understand the discussion above to mean the PR is obsoleted.

2026-01-15 01:45 UTC, closed without merging