Deprecation of MCMT in favor of MCMTGate
Qiskit/qiskit pull request #13584
Opened 2024-12-19 17:38 UTC by 1ucian0

The Multiple-Control-Multiple-Target in `qiskit.circuit.library.generalized_gates.MCMT` was pending for deprecation in https://github.com/Qiskit/qiskit/pull/13150 . This PR moves it to deprecated.

2024-12-20 08:02 UTC, Cryoris commented
I think we want to deprecate the circuit library objects for 1.4 and 2.0, but might not want to remove them for 2.0. Even though this PR only changes from `PendingDeprecationWarning` to `DeprecationWarning`, we probably should discuss what the exact plan is 🙂

2025-02-05 18:03 UTC, Cryoris commented on releasenotes/notes/followup_13150-5bd0c77248601e1a.yaml
> +    and replaced by :class:`MCMTGate`, which is a proper :class:`Gate` subclass.
```suggestion
    and replaced by :class:`.MCMTGate`, which is a proper :class:`.Gate` subclass. Using
    a gate instead of a circuit allows the compiler to reason about the object at a higher
    level of abstraction and allows for multiple synthesis plugins.
```

2025-02-05 18:03 UTC, Cryoris approved these changes

2025-02-05 18:05 UTC, Cryoris requested changes
Sorry I was too eager to approve -- this should actually be merged both into 2.0 and 1.4 since we want to keep the `MCMT` circuit (and all other library objects) deprecated throughout the 2.0 cycle and only remove them in 3.0.

2025-02-05 21:35 UTC, 1ucian0 commented
@mergifyio backport stable/1.4

2025-02-06 08:37 UTC, Cryoris submitted a review, later dismissed
Thanks!

2025-02-07 15:21 UTC, Cryoris approved these changes

2025-02-07 15:59 UTC, merged