fixed issue 8438 PauliList.evolve raises exception
Qiskit/qiskit pull request #8453
Opened 2022-08-04 15:22 UTC by BramDo

### Summary
This pull request is fix for issue 8438 
Title
PauliList.evolve raises exception when evolving certain Clifford circuits

### Details and comments

changed in file base_pauli.py

if dtype is None:
    dtype = np.min_scalar_type(x.shape[axis])

2022-08-04 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8453) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8453) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=8453) it.</sub>

2022-08-05 00:09 UTC, ikkoham commented
Great! Thank you for fixing the bug. This fix looks good.
Could you add some tests for this problem and [release note](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#release-notes)?

2022-08-05 12:22 UTC, BramDo commented
> Great! Thank you for fixing the bug. This fix looks good. Could you add some tests for this problem and [release note](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#release-notes)?

I will add the test and release not, but I have to find out how to do this.

2022-08-07 19:29 UTC, BramDo commented
added test
test_evolve_clifford_with_phase()

added release note
[releasenotes/notes/fix_evolve_raises_exception_in_Cliffordcircuits

2022-08-08 14:37 UTC, ikkoham reviewed
LGTM, I left a minor comment.

2022-08-08 14:37 UTC, ikkoham commented on test/python/quantum_info/operators/symplectic/test_pauli.py
> +import qiskit.quantum_info as qi
```suggestion
```

2022-08-08 14:37 UTC, ikkoham commented on test/python/quantum_info/operators/symplectic/test_pauli.py
> +        pauli = qi.random_pauli(2, seed=123)
```suggestion
        pauli = random_pauli(2, seed=123)
```

2022-08-08 15:50 UTC, ikkoham approved these changes
Thank you. LGTM

2022-08-15 17:49 UTC, jakelishman requested changes
I'm not certain this is the fully correct solution to the problem here - see https://github.com/Qiskit/qiskit-terra/issues/8438#issuecomment-1215496035 for my other reasoning.

2022-08-17 14:10 UTC, ikkoham commented
＠jakelishman You are completely right. We should pass dtype when we call  `_count_y` if it takes mod 2 or 4. This fix would be a performance regression, so it was a not good. (I withdraw my initial approval.)

2022-08-23 12:00 UTC, BramDo commented
As already discussed it is not necessary to modify the _count_y because dtype handling there looks correct for what the function does. The more correct solution is to ensure that whatever's calling that is passing np.uint8 as the dtype when it's going to bind the result to a uint8 context, or it manually cast. The caller can be found in the exception handling of the example:

~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/base_pauli.py in _evolve_cz(base_pauli, q1, q2) 661 base_pauli._z[:, q1] ^= x2 662 base_pauli._z[:, q2] ^= x1 --> 663 base_pauli._phase += 2 * np.logical_and(x1, x2).T 664 return base_pauli 665

In the example we use an evolve over the phase. This is done by the evolve_cz function. In line 663 the phase vector is set by:
base_pauli._phase += 2 * np.logical_and(x1, x2).T

To cast the phase vector to a uint8 we can do:
base_pauli._phase += np.uint8(2 * (np.logical_and(x1, x2).T))

Summary
No change in the _count_y function but modification of the result of the _evolve_cz function. This works, I got the mathematically correct answer as before and we don't have to change the phase vector from what it logically should be (u8) to something much wider (i64) with the problem of using to much data all the time.

I'll be happy to go further with this PR if this is the way to go.

2024-02-23 01:11 UTC, closed without merging

2024-02-23 01:11 UTC, jakelishman commented
Sorry for the lack of responses here.  The underlying issue appears to have been fixed by #8877, so I'll close this PR as obsolete now, but please feel free to open another PR if I've missed anything.