Mcx recursive
Qiskit/qiskit pull request #8710
Opened 2022-09-08 18:18 UTC by adjs

Co-Authored-By: Rafaella Vale <26910380+rafaella-vale@users.noreply.github.com>
Co-Authored-By: Jefferson Deyvis <67497412+jeffersondeyvis@users.noreply.github.com>
Co-Authored-By: @adjs 

### Summary
Issue #5872 
Change the recursive method for the Lemma 9 of arXiv:1501.06911, first shown in Lemma 7.3 of https://link.aps.org/doi/10.1103/PhysRevA.52.3457

### Details and comments
For the case of num_qubits>5 we changed the recursion method for a method which divides the control qubits in two groups, and them apply the MCXVChain gate alternating between the two groups.

2022-09-08 18:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8710) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8710) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: thiagom123<br/>:x: rafaella-vale<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=8710) it.</sub>

2022-09-08 23:36 UTC, adjs commented on test/python/circuit/test_circuit_qasm.py
> +
```suggestion
```

2022-09-09 15:38 UTC, rafaella-vale commented on test/python/circuit/test_circuit_qasm.py
> +
Sorry, I forgot.

2023-03-06 20:25 UTC, adjs commented
This PR solves issue #9743.

The number of cx gates will be further reduced with PR #9687.

2024-03-17 13:41 UTC, ShellyGarion requested changes
Thanks @adjs for your contribution. 
This PR is waiting for #9687 to get merged. 
There are some conflicts that should be fixed afterwards.

Is there some bound on the number of `CX` gates? If so - could you please add it to the docs and add proper tests?

Generally, the name `MCXRecursive` is a bit misleading now, since it's not a recursive algorithm anymore. It basically handles the case of one clean ancilla qubit. We don't want to update the class name now (maybe we will have a unified API of MCX gates towards Qiskit 2.0), but the docstring of the `MCXRecursive` class should be updated to better explain this, also add a reference to the relevant paper and theorem. Perhaps even some examples if possible?
Release notes are also needed.

In addition, in #9687 you introduced two parameters: `relative_phase, action_only` for the `MCXVChain` class. 
Does any of these parameters can also improve the number of `CX` gates in the  `MCXRecursive` class?

2024-07-07 06:42 UTC, ShellyGarion commented
Thank you very much for your contribution to Qiskit @adjs! 
Now that #9687 has been merged, could you please rebase your PR on Qiskit main branch, add some release notes and tests, and relate to my comment above?
We are very much interested in merging this PR for Qiskit 1.2 release

2024-07-15 06:50 UTC, ShellyGarion commented
I'm closing this PR in favor of #12772, so we'll be able to make it for Qiskit 1.2 release. All your commits appear there as well.
Thank you very much for your contribution to Qiskit!

2024-07-15 06:50 UTC, closed without merging