Reduce redundant circuit copies and parameter bindings
Qiskit/qiskit pull request #9228
Opened 2022-12-02 08:12 UTC by n-ejima

### Summary

The current code has these two issues:
1. QuantumCircuit is copied at every parameter binding, but the old copies are not used repeatedly.
2. All of the parameters included in QuantumCircuit are updated even when the values of parameters are not changed.

I fixed the above issues by:
1. Copying each of transpiled circuits only once and reusing the single copy per circuit.
2. Only updating the parameters whose values are different from the previous ones. 
  - This can be done because parameter values remain in transpiled circuits by reusing the copied circuits.

### Details and comments

2022-12-02 08:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=9228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=9228) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=9228) it.</sub>

2022-12-02 08:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=9228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=9228) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=9228) it.</sub>

2022-12-02 10:41 UTC, ikkoham requested changes
@n-ejima Thank you for your first contribution. Your proposal is great!

This PR seems like it would definitely improve the performance of VQE. Do you have any benchmarking results? The benchmark can show the impact of this PR.

For the code, we don't want to change the `QuantumCircuit` class if possible. The type signature change of `.assign_parameters` affects the linter (CI fails).  Therefore, I propose to create a method inside CircuitSampler that is assigning parameters to `QuantumCircuit`.

2022-12-02 11:16 UTC, jakelishman requested changes
This PR is suggesting a massive mix-up of object ownership semantics that I don't think is safe to bring near `QuantumCircuit`, and will be fragile even for use within `opflow`.  I would suggest that if `opflow` _deliberately_ wants to share ownership of various internal objects that it can guarantee no references to will leak out to users and each object will only be mutated once, it's going to need to do its own thing a little bit; I'm not comfortable adding these changes into `QuantumCircuit` itself.

On a second note: with the deprecation of `opflow` pending, is this something we need to pursue?  How does the non-deprecated replacement for this behave?

2022-12-02 14:56 UTC, woodsp-ibm commented
> with the deprecation of opflow pending, is this something we need to pursue?

I don't think so, if the focus here is really around opflow and CircuitSampler. The author may not have known that, with the refactoring of algorithms over to using primitives in the last release, that the former algorithms and the way they worked, along with opflow and QuantumInstance they used, will shortly be deprecated and removed thereafter.

2022-12-02 15:52 UTC, jakelishman commented
Thanks Steve - for sure, I wasn't suggesting it was your fault here @n-ejima, sorry that wasn't clear.

2022-12-05 06:36 UTC, n-ejima commented
> @n-ejima Thank you for your first contribution. Your proposal is great!
> 
> This PR seems like it would definitely improve the performance of VQE. Do you have any benchmarking results? The benchmark can show the impact of this PR.

This graph shows the processing time of parameter bindings when running VQE in below experimental environment. Circuit copy and parameter assignment account for a large part of parameter bindings. 
This PR can reduce a large amount of processing time of parameter bindings.

![image](https://user-images.githubusercontent.com/117971374/205563215-9544b376-4138-46ab-ac07-12c4b6a70c9a.png)

![image](https://user-images.githubusercontent.com/117971374/205560158-5e6fab72-6d53-42d6-b402-bc71f47b9ade.png)

2022-12-22 07:31 UTC, n-ejima commented
I fixed the code not to change QuantumCircuit class. With this fixing, the 2nd issue I mentioned is not resolved. I think only reducing the number of circuit copy (1st issue) has enough effect to the performance.
- Result of executing VQE on the H8 molecule (# of qubit:13, # of parameter:184,# of iteration:1861)  
  - total executing time of assign_parameter
    - before fixing: 888 sec, overall VQE executingtime: 2015 sec
    - reducing circuit copy: 167 sec (assign_parameter + processing to reduce circuit copy), overall VQE executing time: 1210 sec

2023-01-10 02:59 UTC, ikkoham reviewed
Sorry for my lazy review.

The direction (reduce redundant circuit copies) seems nice. The performance improvement is significant and may be use the same idea in primitives.
I have minor comments to improve codes.

2023-01-10 02:59 UTC, ikkoham commented on qiskit/opflow/converters/circuit_sampler.py
> +
These codes should be outside of `try`.

2023-01-10 02:59 UTC, ikkoham commented on qiskit/opflow/converters/circuit_sampler.py
> +                    shadow._increment_instances()
Do we need `_increment_instances` and `_name_update` here?

2023-01-10 02:59 UTC, ikkoham commented on qiskit/opflow/converters/circuit_sampler.py
> +                append_size = len(param_bindings) - len(self._reuse_circs[0])
If the length of param_bindings is smaller on the second calls, won't this be a negative number?

2023-01-10 02:59 UTC, ikkoham commented on qiskit/opflow/converters/circuit_sampler.py
> +                for param in self._reuse_parameter_tables[i][j]:
`self._reuse_parameter_tables[i][j].items()` is readable since `self._reuse_parameter_tables[i][j][param]` is frequently appeared.

2023-01-10 02:59 UTC, ikkoham commented on qiskit/opflow/converters/circuit_sampler.py
> +                            .__getstate__()[k][0]
Is it difficult to avoid using `__getstatete__`?

2023-01-10 16:43 UTC, Cryoris commented
It's definitely great to reduce copies, however I'm not quite sure that this is the right approach here. If I understand correctly, the idea is to directly change the parameters inside the `instruction.params` and avoid going through `.bind_parameters`, right? 

This approach is a bit volatile as e.g. parameter changes are not propagated down to sub-instructions and decomposing the circuit will lose the parameter assignment. There are two other ways we could implement this or speed up the assignment generally:
* general speedup: make circuit copies fast by taking the parameter out of the instruction (see #3800), this is something @jakelishman is already preparing
* make parameters re-assignable: this is closer to the approach in this PR and would mean that we refactor the parameters to additionally store a value they are currently assigned to and make the backends handle these new types

2023-01-11 07:32 UTC, ikkoham commented
@Cryoris Thanks. `QuantumCircuit`'s deepcopy speedup should be done. This is a problem in many areas, not just this one.

I think the approach of making reassignable is nice. However, I personally do not want to change `QC` it's already too complicated. If someone could do it by 0.24, I agree that we wait for that change and then allow this PR to use re-assign.

2023-01-12 00:52 UTC, n-ejima commented
@Cryoris 
> If I understand correctly, the idea is to directly change the parameters inside the instruction.params and avoid going through .bind_parameters, right?

I don't intended to update the parameters without `assign_parameter()`.  In my approach, parameters are updated by `assign_prameters()`, and after executing the quantum circuit, parameters are restored to its original state like `0.5 * t[0]` maintaining both QuantumCircuit and QC's ParameterTable have the same `instruction.params` instance.  

> make parameters re-assignable: this is closer to the approach in this PR and would mean that we refactor the parameters to additionally store a value they are currently assigned to and make the backends handle these new types

As @ikkoham said, if QC will be modified to have both original and assigned parameters, I want to wait for it.

2023-02-02 07:04 UTC, ikkoham commented
@Cryoris Do you have a plan to implement re-assignable parameters for 0.24?

2023-04-19 19:04 UTC, Cryoris commented
We discussed this in the team and came to the conclusion that we would rather not include this PR into the release, for two main reasons
1. This is a workaround for the expensive circuit copies, which we are currently working to resolve. With light-weight circuits, this workaround would not be necessary anymore and the problem is properly fixed, without the trouble of mixed ownerships mentioned above 
2. Opflow is being deprecated in this release, so adding a workaround solution as this adds a lot of overhead to code that will be removed soon.

Your benchmarks are definitely impressive and also serve as a good indicator of how much faster Qiskit can be, once the circuits are efficiently copied 🙂 I hope this makes sense to you, let me know if you want to discuss further!

2023-12-19 13:07 UTC, jakelishman commented
I'm sorry that we couldn't move this to merge at the time.  Now that `opflow` has been removed, as of #11111, this PR is obsolete, so I'm going to close it.  Thanks for the effort at the time, and sorry that it didn't merge while opflow was live.

2023-12-19 13:07 UTC, closed without merging